project:
  type: website

website:
  title: "terrameta"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
  search: false

format:
  html:
    theme:
      - cosmo
      - brand
    css: css/custom.css
    toc: true
    page-layout: full



